application: house-expense
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets
  
- url: /
  script: pages.application
  
- url: /users
  script: pages.application
  
- url: /residents
  script: pages.application

- url: /register
  script: pages.application
  
- url: /transactions
  script: pages.application
  
- url: /summary
  script: pages.application
  
- url: /monthlysummary
  script: pages.application

- url: /transaction/.*
  script: transactioncrud.application

- url: /summary/.*
  script: summarycrud.application

- url: /user/.*
  script: usercrud.application
  
- url: /resident/.*
  script: residentcrud.application



libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
