application: your-app-id
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /admin.*
  script: admin.application
  
- url: /register
  script: admin.application
  
- url: /transaction/.*
  script: transactioncrud.application

- url: /summary/.*
  script: summarycrud.application

- url: /transactions
  script: transactions.application
  
- url: /summary.*
  script: summary.application

- url: /user/.*
  script: usercrud.application

- url: /users
  script: users.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
